site_name: Association of Marine Corps Logisticians
site_url: https://www.marinecorpslogistics.org/
# site_url: https://marines.dev/
site_description: "Marine Coders is a community of Marine Corps stakeholders, active duty, reserve, retired, civilian, etc., that are interested in improving the force through software development."

edit_uri: ""

theme:
  name: material
  custom_dir: docs/overrides
  language: en

  icon:
    repo: fontawesome/brands/github
  favicon: assets/amcl_logo.png
  logo: assets/amcl_logo.png
  font:
    text: Roboto
  palette:
    - scheme: amcl-light
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: amcl-dark
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - announce.dismiss
    
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - def_list
  - toc:
      permalink: ⚓︎
  - footnotes
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.progressbar
  - tables
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - social:
      cards_color:
        fill: "#252a34" 
        text: "#FFFFFF"
  - blog:
      authors_file: .authors.yml
      authors_in_excerpt: 2
  - meta:
      meta_file: '**/.meta.yml' 
  - search
  - tags:
      tags_file: blog/tags.md
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/marinecoders
    - icon: fontawesome/brands/gitlab
      link: https://web.git.mil/marine-coders
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/marine-coders
    - icon: fontawesome/solid/square-rss
      link: https://marines.dev/feed_rss_created.xml
      
copyright: >
  Copyright &copy; 2023 Association of Marine Corp Logisticians. Proudly created by Marine Coders

nav:
  - Home: /
  - Leadership: leadership.md
  - The Log Blog:
    - blog/index.md 
  - Chapters: /projects
  - Partners: /opportunities
  - Groups: /chat
  - About: /about

banner:
  title: Not Official Marine Corps Website
  dropdown:
    left: >
      <strong>Official websites use .mil</strong><br>
      Pursuant to MCO 5030.3B:  Neither the United States Marine Corps nor any other component of the Department of Defense (DoD) has approved, endorsed, or authorized this activity. The appearance of U.S. DoD visual information does not imply or constitute DoD endorsement. A .mil website belongs to an official government organization
      in the United States.
    right: >
      <strong>Secure .org websites use HTTPS</strong><br>
      A lock (<span class="icon-lock">🔒</span>) or https:// means you've safely connected to the .org website. Share
      sensitive information only on official, secure websites.