collin.chew:
  name: Capt Collin Chew
  description: Co-Founder
  avatar: /assets/authors/collinchew.jpeg
drew.hutch:
  name: Maj Drew Hutcheon
  description: Co-Founder
  avatar: /assets/authors/drewhutch.jpeg
william.crum:
  name: Cpl William Crum
  description: Marine Coder
  avatar: /assets/authors/elisoncrum.jpeg
matt.evers:
  name: Matt Evers
  description: AMCL Vice President of Operations
  avatar: /assets/authors/mattevers.jpeg