name: Custom MkDocs Build and Deploy
on:
  push:
    branches:
      - master
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install pillow cairosvg mkdocs-rss-plugin
      - run: git clone -b $mkdocs_material_tag https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders
      - run: pip install -e mkdocs-material-insiders
      - run: mkdocs gh-deploy --force
env:
  mkdocs_material_tag: 8.5.7-insiders-4.26.1
  GH_TOKEN: ${{ secrets.GH_TOKEN }} 